public:
  name: public-proxy-1
  database_file: /tmp/public-proxy-announcements.db
  tls_bind_address: localhost:4433
  internal_bind_address: localhost:9999
  jsonrpc_client:
    endpoint: https://localhost:5544/jsonrpc
    server_name: public-proxy-1
    tls:
      ca_certificate_file: "$DIR/../../certs/root.crt"
      certificate_file: "$DIR/../../certs/public-proxy-1.crt"
      key_file: "$DIR/../../certs/public-proxy-1.key"
  jsonrpc_server: # the JSON-RPC server that the EPS server uses for communication
    bind_address: "localhost:6655"
    cors:
      allowed_hosts: ["^http(?:s)?://localhost\\:\\d+$"]
    tls:
      ca_certificate_file: "$DIR/../../certs/root.crt"
      certificate_file: "$DIR/../../certs/public-proxy-1.crt"
      key_file: "$DIR/../../certs/public-proxy-1.key"
      validate_client: false