name: private-proxy-1
directory:
# to use the JSON directory, uncomment this and comment everything below...
  type: json
  settings:
    path: "$DIR/../../directory"
#  type: api
#  settings:
#    jsonrpc_client:
#      tls:
#        certificate_file: "$DIR/../../certs/hd-1.crt"
#        key_file: "$DIR/../../certs/hd-1.key"
#        ca_certificate_file: "$DIR/../../certs/root.crt"
#    ca_certificate_file: "$DIR/../../certs/root.crt"
#    endpoints: ["https://localhost:3322/jsonrpc"]
#    server_names: ["sd-1"]
channels: # defines all the channels that we want to open when starting the server
  - name: main gRPC server # accepts incoming gRPC connections to deliver and receive messages
    type: grpc_server
    settings:
      bind_address: "localhost:7776"
      tls:
        ca_certificate_file: "$DIR/../../certs/root.crt"
        certificate_file: "$DIR/../../certs/private-proxy-1.crt"
        key_file: "$DIR/../../certs/private-proxy-1.key"
  - name: main gRPC client # creates outgoing gRPC connections to deliver and receive messages
    type: grpc_client
    settings:
      tls:
        ca_certificate_file: "$DIR/../../certs/root.crt"
        certificate_file: "$DIR/../../certs/private-proxy-1.crt"
        key_file: "$DIR/../../certs/private-proxy-1.key"
  - name: main JSON-RPC server # accepts incoming JSONRPC connections to deliver and receive messages
    type: jsonrpc_server 
    settings:
      bind_address: "localhost:7766"
      cors:
        allowed_hosts: ["^http(?:s)?://localhost\\:\\d+$"]
      tls:
        ca_certificate_file: "$DIR/../../certs/root.crt"
        certificate_file: "$DIR/../../certs/private-proxy-1.crt"
        key_file: "$DIR/../../certs/private-proxy-1.key"
  - name: main JSON-RPC client # creates outgoing JSONRPC connections to deliver and receive messages
    type: jsonrpc_client
    settings:
      endpoint: http://127.0.0.1:8877/jsonrpc
      #tls:
      #  ca_certificate_file: "$DIR/../../certs/root.crt"
